### ISSUE TITLE
Wrong automatic clue counts announced for spymaster

### ISSUE THREAD

**Issue by SayantaBhar** [dperelman/clues-for-two#20]
Sometimes spymaster is clicking clue words and announcing the clue but it announces n number of clue counts whereas n+1 clue words are highlighted.
This happened 3-4 times for some friends in our group, I am yet to reproduce it myself.

**Comment by dperelman** [comment]
Weird. Thanks for the bug report. I'll investigate.

One thing I can think of is that it updates the clue count separately from highlighting the clue, so there's definitely a race where in theory if you click a word and then submit the clue fast enough, it won't have time to change the count... I'm not sure how that would actually happen in practice, though. I could fix the race by forcing the client to wait for a response to it clicking on the card, I guess.

**Comment by dperelman** [comment]
05953040c2652f7a12faffc8ae1039991d16be5b fixes the race condition. 66aeae368b7547d143e16d13e7fadcc86619bc92 changes the code to update `clueWords` to use a [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set). Not sure if either actually has anything to do with the bug, but they seem like good ideas that don't break anything.

**Comment by SayantaBhar** [comment]
> [0595304](https://github.com/dperelman/codenames.plus/commit/05953040c2652f7a12faffc8ae1039991d16be5b) fixes the race condition. [66aeae3](https://github.com/dperelman/codenames.plus/commit/66aeae368b7547d143e16d13e7fadcc86619bc92) changes the code to update `clueWords` to use a [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set). Not sure if either actually has anything to do with the bug, but they seem like good ideas that don't break anything.

I will let you know after these fixes if it comes up again while we are playing. Let's wait for few days and then accordingly we can close/investigate.

**Comment by SayantaBhar** [comment]
Closing as didn't reproduce after the fix.
