### ISSUE TITLE
Keep time slider above the card packs or somewhere visible in the screen.

### ISSUE THREAD

**Issue by SayantaBhar** [dperelman/clues-for-two#23]
Sometimes we change the time slider say from 30 seconds to 60 seconds. So, need to scroll down to see that slider after all the card packs. But card packs are usually not changed, so, make sense to put the slider above the card packs or at some other suitable place.

**Comment by dperelman** [comment]
My friends don't use the timed mode, so I don't have any strong opinions on the UI for it. Play around with HTML/CSS for it and I'll pull your changes.

**Comment by SayantaBhar** [comment]
Closing this, as in reality most people make max 4-5 packs visible in which case time slider is easily accessible.
